params:
  - src/config/config.yaml

stages:
  constitucion_cr_raw:
    cmd: wget 
      http://www.pgrweb.go.cr/TextoCompleto/NORMAS/1/VIGENTE/C/1940-1949/1945-1949/1949/367/871_138995-26.html
      --output-document=data/rawdata/constitucion_cr-26.html
    outs:
    - data/rawdata/constitucion_cr-26.html

  constitucion_cr:
    deps:
      - data/rawdata/constitucion_cr-26.html
      - src/legalogic/prep_docs/prep_const.py
    cmd: >
      python
      src/legalogic/prep_docs/prep_const.py -v
      data/rawdata/constitucion_cr-26.html
      >data/preprocessed/constitucion_cr-26.txt
    outs:
    - data/preprocessed/constitucion_cr-26.txt
