#!/usr/bin/env python

"""
Analyze stats of nodes found in constitutional parse.
"""

from collections import Counter

node_count = Counter(
    {
        ('sn', 'spec', 'grup.nom'): 1638,
        ('spec', 'DET'): 1570,
        ('prep', 'ADP'): 1055,
        ('sp', 'prep', 'sn'): 792,
        ('sn', 'grup.nom'): 684,
        ('ROOT', 'sentence'): 612,
        ('grup.nom', 'NOUN'): 545,
        ('grup.verb', 'VERB'): 462,
        ('conj', 'CCONJ'): 375,
        ('grup.nom', 'NOUN', 'sp'): 346,
        ('infinitiu', 'VERB'): 325,
        ('grup.nom', 'NOUN', 's.a'): 197,
        ('sadv', 'grup.adv'): 189,
        ('grup.adv', 'ADV'): 164,
        ('participi', 'ADJ'): 159,
        ('grup.nom', 'PROPN'): 147,
        ('grup.nom', 'NOUN', 'S'): 131,
        ('grup.nom', 'NUM'): 131,
        ('grup.verb', 'AUX'): 125,
        ('morfema.verbal', 'PRON'): 116,
        ('grup.nom', 'PRON'): 113,
        ('grup.nom', 'NOUN', 's.a', 'sp'): 111,
        ('conj', 'SCONJ'): 108,
        ('neg', 'ADV'): 103,
        ('grup.verb', 'AUX', 'infinitiu'): 100,
        ('S', 'infinitiu', 'sn'): 91,
        ('sn', 'sn', 'conj', 'sn'): 86,
        ('sn', 'grup.nom', 'PUNCT'): 85,
        ('grup.nom', 'PROPN', 'PROPN'): 77,
        ('prep', 'grup.prep'): 75,
        ('S', 'S', 'conj', 'S'): 69,
        ('grup.nom', 'PROPN', 'sp'): 68,
        ('s.a', 'grup.a'): 68,
        ('sp', 'prep', 'S'): 61,
        ('grup.prep', 'prep', 'sn', 'prep'): 58,
        ('grup.a', 'ADJ'): 56,
        ('sentence', 'sn', 'grup.verb', 'sn', 'PUNCT'): 55,
        ('grup.nom', 'NOUN', 's.a', 'sp', 'sp'): 54,
        ('morfema.pronominal', 'PRON'): 52,
        ('sp', 'prep', 'sn', 'PUNCT'): 52,
        ('sentence', 'S', 'conj', 'S', 'PUNCT'): 48,
        ('grup.verb', 'AUX', 'VERB'): 45,
        ('spec', 'DET', 'DET'): 43,
        ('sentence', 'PUNCT', 'sadv', 'participi', 'sp', 'PUNCT'): 41,
        ('S', 'infinitiu'): 40,
        ('sp', 'PUNCT', 'prep', 'sn'): 39,
        ('sn', 'spec', 'grup.nom', 'PUNCT'): 38,
        ('grup.nom', 'NOUN', 's.a', 'S'): 38,
        ('sentence', 'sn', 'grup.verb', 'sp', 'PUNCT'): 37,
        ('S', 'participi', 'sp'): 36,
        ('sp', 'PUNCT', 'prep', 'sn', 'PUNCT'): 36,
        ('spec', 'NUM'): 36,
        ('grup.nom', 'NOUN', 'sn', 'sp'): 36,
        ('grup.nom', 'PROPN', 'PROPN', 'sp'): 36,
        ('S', 'sn', 'S'): 36,
        ('grup.nom', 'S'): 33,
        ('sp', 'sp', 'conj', 'sp'): 33,
        ('grup.verb', 'AUX', 'infinitiu', 'morfema.pronominal'): 30,
        ('grup.nom', 'NOUN', 'sp', 'sp'): 30,
        ('grup.nom', 'grup.nom', 'sp'): 29,
        ('infinitiu', 'AUX', 'VERB'): 28,
        ('grup.adv', 'ADV', 'sp'): 27,
        ('sentence', 'S', 'PUNCT', 'S', 'PUNCT'): 23,
        ('grup.nom', 'NOUN', 'sp', 'S'): 22,
        ('infinitiu', 'AUX'): 22,
        ('grup.nom', 's.a', 'NOUN'): 21,
        ('spec', 'PRON'): 21,
        ('S', 'sn', 'grup.verb', 'sn'): 20,
        ('sn', 'sn', 'PUNCT', 'sn', 'conj', 'sn'): 20,
        ('grup.nom', 'grup.nom', 'S'): 20,
        ('grup.nom', 's.a'): 20,
        ('grup.nom', 'grup.nom', 'conj', 'grup.nom'): 20,
        ('S', 'grup.verb', 'sn'): 19,
        ('S', 'grup.verb'): 19,
        ('gerundi', 'VERB'): 18,
        ('inc', 'sn'): 18,
        ('sadv', 'grup.adv', 'PUNCT'): 17,
        ('sentence', 'sn', 'PUNCT'): 17,
        ('S', 'participi'): 17,
        ('grup.nom', 's.a', 'NOUN', 'sp'): 16,
        ('grup.adv', 'sp'): 16,
        ('grup.a', 'ADJ', 'sp'): 16,
        ('grup.nom', 'NOUN', 's.a', 's.a'): 15,
        ('S', 'infinitiu', 'sn', 'sp'): 14,
        ('ROOT', 'S'): 14,
        ('spec', 'DET', 'NUM'): 14,
        ('S', 'infinitiu', 'sp'): 14,
        ('sp', 'PUNCT', 'prep', 'S'): 14,
        ('S', 'sn', 'sp'): 13,
        ('sn', 'sn', 'sp'): 13,
        ('sentence', 'sn', 'grup.verb', 'S', 'PUNCT'): 12,
        ('sentence', 'sn', 'grup.verb', 'sn', 'sp', 'PUNCT'): 12,
        ('relatiu', 'PRON'): 12,
        ('S', 'grup.verb', 'sp'): 12,
        ('S', 'sn', 'grup.verb', 'sp'): 12,
        ('prep', 'SCONJ'): 11,
        ('sentence', 'S', 'S', 'PUNCT'): 11,
        ('sp', 'prep', 'S', 'PUNCT'): 11,
        ('grup.nom', 'PROPN', 'S'): 11,
        ('sentence', 'sn', 'grup.verb', 's.a', 'PUNCT'): 10,
        ('conj', 'grup.cc'): 10,
        ('S', 'sn', 'grup.verb'): 10,
        ('S', 'S', 'sn'): 10,
        ('grup.nom', 'grup.w', 'sp'): 10,
        ('S', 'S', 'PUNCT', 'S', 'conj', 'S'): 9,
        ('conj', 'grup.cs'): 9,
        ('sadv', 'PUNCT', 'grup.adv', 'PUNCT'): 9,
        ('S', 'PUNCT', 'participi', 'sp', 'PUNCT'): 9,
        ('sentence', 'sn', 'S'): 9,
        ('sentence', 'sentence'): 8,
        ('grup.nom', 'PRON', 'sp'): 8,
        ('grup.cc', 'ADV', 'SCONJ'): 8,
        ('S', 'infinitiu', 'sp', 'sn'): 8,
        ('S', 'infinitiu', 'S'): 8,
        ('grup.nom', 'NOUN', 'sn'): 8,
        ('grup.nom', 'NOUN', 'S', 'sp'): 8,
        ('infinitiu', 'grup.verb'): 8,
        ('grup.verb', 'AUX', 'grup.verb'): 8,
        ('S', 'sn'): 8,
        ('sentence', 'sn', 'PUNCT', 'S', 'PUNCT'): 8,
        ('grup.nom', 'PROPN', 's.a'): 7,
        ('sn', 'sn', 'S'): 7,
        ('S', 'conj', 'grup.verb', 'sn'): 7,
        ('grup.nom', 'NOUN', 'sn', 'sp', 'sp'): 7,
        ('grup.verb', 'AUX', 'infinitiu', 'sn'): 7,
        ('sentence', 'sn', 'grup.verb', 'sp', 'sp', 'PUNCT'): 7,
        ('grup.nom', 's.a', 'NOUN', 'S'): 7,
        ('S', 'sadv', 'participi', 'sp'): 7,
        ('grup.nom', 'PROPN', 'NUM'): 7,
        ('grup.prep', 'ADV', 'ADP'): 7,
        ('S', 'sn', 'grup.verb', 'sn', 'PUNCT'): 7,
        ('S', 'infinitiu', 'sp', 'sp'): 7,
        ('sn', 'PUNCT', 'grup.nom'): 6,
        ('grup.nom', 'NOUN', 'sp', 's.a'): 6,
        ('S', 'grup.verb', 'S'): 6,
        ('sentence', 'morfema.verbal', 'grup.verb', 'sn', 'PUNCT'): 6,
        ('S', 'conj', 'S', 'conj', 'S'): 6,
        ('grup.nom', 's.a', 'NOUN', 's.a'): 6,
        ('sentence', 'sn', 'grup.verb', 'sp', 'sn', 'PUNCT'): 6,
        ('infinitiu', 'NOUN'): 6,
        ('sentence', 'sn'): 6,
        ('S', 'S', 'S'): 5,
        ('S', 'S', 'PUNCT', 'S'): 5,
        ('grup.prep', 'NOUN', 'ADP'): 5,
        ('conj', 'sp'): 5,
        ('grup.cc', 'PART', 'NOUN'): 5,
        ('sentence', 'S', 'PUNCT'): 5,
        ('S', 'neg', 'grup.verb', 'sn'): 5,
        ('S', 'conj', 'morfema.verbal', 'grup.verb', 'sp'): 5,
        ('S', 'sp', 'morfema.verbal', 'grup.verb', 'sn'): 5,
        ('sp', 'sp', 'PUNCT'): 5,
        ('sentence', 'sn', 'neg', 'grup.verb', 'sp', 'PUNCT'): 5,
        ('sn', 'grup.z'): 5,
        ('sn', 'PUNCT', 'grup.nom', 'PUNCT'): 5,
        ('grup.nom', 'ADJ'): 5,
        ('S', 'sn', 'infinitiu', 'sn'): 5,
        ('sentence', 'sn', 'grup.verb', 'sadv', 'sp', 'PUNCT'): 4,
        ('sn', 'sn', 'PUNCT', 'sn', 'conj', 'sn', 'PUNCT'): 4,
        ('sp', 'sp', 'PUNCT', 'sp'): 4,
        ('S', 'participi', 'sp', 'sp'): 4,
        ('S', 'conj', 'sn', 'grup.verb', 'sp'): 4,
        ('sentence', 'sp', 'grup.verb', 'sn', 'PUNCT'): 4,
        ('grup.nom', 's.a', 'sp'): 4,
        ('S', 'relatiu', 'grup.verb', 'sn'): 4,
        ('conj', 'PRON'): 4,
        ('S', 'infinitiu', 'morfema.pronominal', 'sp'): 4,
        ('S', 'grup.verb', 's.a'): 4,
        ('S', 'conj', 'sn'): 4,
        ('S', 'S', 'conj', 'S', 'PUNCT'): 4,
        ('grup.cs', 'ADV', 'SCONJ'): 4,
        ('s.a', 'spec', 'grup.a'): 4,
        ('spec', 'ADV'): 4,
        ('sentence', 'neg', 'grup.verb', 'sn', 'PUNCT'): 4,
        ('grup.verb', 'infinitiu', 'NOUN'): 4,
        ('S', 'gerundi', 'sn'): 4,
        ('S', 'sadv', 'grup.verb', 'sp'): 4,
        ('sn', 'sn', 'PUNCT', 'sn', 'PUNCT', 'sn', 'conj', 'sn'): 4,
        ('grup.nom', 'grup.nom', 'PUNCT', 'grup.nom', 'conj', 'grup.nom'): 4,
        ('S', 'participi', 'sn'): 4,
        ('sentence', 'PUNCT'): 4,
        ('grup.adv', 'ADP', 'ADV'): 4,
        ('S', 'sp'): 4,
        ('grup.nom', 'NOUN', 's.a', 'sp', 'S'): 4,
        ('sentence', 'sn', 'grup.verb', 'sn', 'S', 'PUNCT'): 4,
        ('S', 'neg', 'grup.verb'): 4,
        ('S', 'morfema.verbal', 'grup.verb', 'sp'): 4,
        ('grup.nom', 'sp'): 4,
        ('S', 'sn', 'grup.verb', 'sn', 'sp'): 4,
        ('S', 'sn', 'neg', 'grup.verb'): 4,
        ('grup.z', 'NUM', 'SYM'): 4,
        ('S', 'grup.verb', 'sn', 'sp'): 4,
        ('sentence', 'sn', 'morfema.verbal', 'grup.verb', 'sp', 'PUNCT'): 4,
        ('grup.nom', 's.a', 'PROPN'): 4,
        ('S', 'infinitiu', 'sn', 'PUNCT'): 4,
        ('S', 'sn', 'grup.verb', 'S'): 4,
        ('inc', 'inc'): 4,
        ('sp', 'prep', 'sadv'): 4,
        ('S', 'conj', 'S', 'conj', 'S', 'PUNCT'): 4,
        ('S', 'neg'): 4,
        ('sentence', 'sp', 'S', 'PUNCT'): 4,
        ('S', 'sn', 'grup.verb', 'sn', 'sp', 'PUNCT'): 4,
        ('sentence', 'sn', 'sn'): 4,
        ('S', 'S', 'sn', 'PUNCT'): 4,
        ('grup.nom', 'sp', 'S'): 3,
        ('S', 'sadv', 'participi', 'sn', 'sp'): 3,
        ('sentence', 'PUNCT', 'sadv', 'participi', 'sn', 'sp', 'PUNCT'): 3,
        ('sentence', 'sn', 'S', 'PUNCT'): 3,
        ('S', 'infinitiu', 'sp', 'S'): 3,
        ('S', 'PUNCT', 'conj', 'morfema.verbal', 'grup.verb', 'sp'): 3,
        ('grup.nom', 'NOUN', 'S', 'S'): 3,
        ('sn', 'sadv', 'sn'): 3,
        ('sentence', 'grup.verb', 'sn', 'PUNCT'): 3,
        ('S', 'PUNCT', 'S', 'conj', 'S'): 3,
        ('ROOT', 'sn'): 3,
        ('S', 'S', 'PUNCT', 'S', 'PUNCT', 'S'): 3,
        ('S', 'sn', 'grup.verb', 's.a', 'sp'): 3,
        ('conj', 'sp', 'PUNCT'): 3,
        ('S', 'sp', 'grup.verb', 'sn', 'S'): 3,
        ('S', 'infinitiu', 'sn', 'S'): 3,
        ('sentence', 'sadv', 'grup.verb', 'sn', 'PUNCT'): 3,
        ('S', 'sp', 'grup.verb', 'sn'): 3,
        ('sn', 'spec', 'grup.w'): 3,
        ('grup.w', 'NUM', 'sp'): 3,
        ('S', 'sn', 'grup.verb', 's.a'): 3,
        ('sn', 'sn', 's.a'): 3,
        ('sentence', 'sn', 'grup.verb', 'sp', 'S', 'PUNCT'): 3,
        ('S', 'conj', 'sn', 'grup.verb', 'sn'): 3,
        ('sentence', 'sn', 'grup.verb', 'sn', 'sp', 'sp', 'PUNCT'): 3,
        ('S', 'S', 'sp'): 3,
        ('grup.nom', 'PRON', 'S'): 3,
        ('conj', 'grup.cc', 'PUNCT'): 3,
        ('grup.nom', 'grup.z', 'sn'): 3,
        ('grup.nom', 's.a', 'NOUN', 'sn'): 3,
        ('S', 'sn', 'grup.verb', 'sp', 'PUNCT'): 3,
        ('sentence', 'sp', 'sn', 'grup.verb', 'sn', 'PUNCT'): 3,
        ('inc', 'S'): 3,
        ('S', 'conj', 'sn', 'grup.verb', 'sn', 'PUNCT'): 3,
        ('grup.adv', 'INTJ'): 3,
        ('S', 'sadv', 'sp'): 3,
        ('S', 'conj', 'grup.verb', 'sn', 'PUNCT'): 3,
        ('grup.adv', 'ADJ'): 3,
        ('S', 'conj', 'morfema.verbal', 'grup.verb', 'sn', 'PUNCT'): 3,
        ('S', 'sp', 'morfema.verbal', 'grup.verb'): 3,
        ('S', 'conj', 'sn', 'sn', 'grup.verb'): 3,
        ('grup.verb', 'AUX', 'AUX', 'VERB'): 3,
        ('S', 'sn', 'grup.verb', 'sp', 'sp', 'sp', 'PUNCT'): 3,
        ('sentence', 'sn', 'grup.verb', 's.a', 'sp', 'PUNCT'): 3,
        ('sentence', 'S', 'S'): 3,
        ('S', 'sadv', 'participi', 'sn'): 3,
        ('sn', 'sn', 'PUNCT'): 3,
        ('S', 'infinitiu', 'sn', 'sp', 'PUNCT'): 3,
        ('sn', 'spec', 'relatiu'): 3,
        ('S', 'sn', 'morfema.verbal', 'grup.verb', 'sp', 'sp'): 3,
        ('grup.nom', 'S', 'NOUN'): 3,
        ('sadv', 'infinitiu'): 3,
        ('S', 'sn', 'sn', 'sp'): 3,
        ('S', 'grup.verb', 'sp', 'sn'): 3,
        ('sentence', 'S', 'PUNCT', 'S', 'conj', 'S', 'PUNCT'): 2,
        ('grup.verb', 'VERB', 'NOUN'): 2,
        ('grup.nom', 'NOUN', 'sp', 'sp', 'sp', 'sp'): 2,
        ('grup.nom', 'NOUN', 'sp', 'sp', 'sp'): 2,
        ('sn', 'sn', 'conj', 'sn', 'PUNCT'): 2,
        ('sn', 'sn', 'PUNCT', 'sn'): 2,
        ('S', 'sp', 'S'): 2,
        ('grup.nom', 'X'): 2,
        ('sentence', 'sadv', 'sn', 'grup.verb', 'S', 'PUNCT'): 2,
        ('S', 'sn', 'sn', 'grup.verb', 'sp'): 2,
        ('grup.nom', 'NUM', 'sp'): 2,
        ('sp', 'prep', 'sp'): 2,
        ('S', 'infinitiu', 'sn', 'sn', 'sp'): 2,
        ('sentence', 'morfema.verbal', 'grup.verb', 'sn', 'sp', 'PUNCT'): 2,
        ('sn', 'sn', 'conj', 'sp'): 2,
        ('sentence', 'sn', 'sn', 'PUNCT'): 2,
        ('sn', 'PUNCT', 'spec', 'grup.nom', 'PUNCT'): 2,
        ('S', 'conj', 'grup.verb', 'sp', 'sp'): 2,
        ('S', 'sn', 'neg', 'morfema.verbal', 'grup.verb'): 2,
        ('S', 'conj', 'sn', 'grup.verb'): 2,
        ('S', 'S', 'PUNCT'): 2,
        ('sentence', 'grup.verb', 's.a', 'sn', 'PUNCT'): 2,
        ('sentence', 'S', 'PUNCT', 'S', 'conj', 'S', 'sn', 'PUNCT'): 2,
        ('S', 'sadv', 'participi', 'sn', 'sp', 'sp', 'PUNCT'): 2,
        ('S', 'morfema.verbal', 'grup.verb', 'sn'): 2,
        ('sentence', 'PUNCT', 'S', 'PUNCT', 'sn', 'PUNCT'): 2,
        ('sn', 'sn', 'sn', 'sp'): 2,
        ('sentence', 'sn', 'neg', 'grup.verb', 'sn', 'PUNCT'): 2,
        ('S', 'sn', 'participi', 'sp'): 2,
        ('infinitiu', 'infinitiu'): 2,
        ('sentence', 'sp', 'sn', 'grup.verb', 'S', 'PUNCT'): 2,
        ('sp', 'sadv', 'sp'): 2,
        ('grup.cs', 'ADP', 'SCONJ'): 2,
        ('grup.verb', 'VERB', 'infinitiu'): 2,
        ('sn', 'sp', 'sn'): 2,
        ('sentence', 'S', 'sn', 'grup.verb', 'sn', 'PUNCT'): 2,
        ('S', 'gerundi', 'sp', 'PUNCT'): 2,
        ('grup.verb', 'AUX', 'ADP', 'infinitiu'): 2,
        ('spec', 'ADV', 'ADP', 'DET'): 2,
        ('S', 'conj', 'morfema.verbal', 'grup.verb', 'sn'): 2,
        ('S', 'S', 'PUNCT', 'sn'): 2,
        ('S', 'conj', 'sn', 'grup.verb', 's.a'): 2,
        ('grup.verb', 'ADJ'): 2,
        ('S', 'PUNCT', 'conj', 'grup.verb', 'sp'): 2,
        ('sentence', 'sp', 'morfema.verbal', 'grup.verb', 'sn', 'PUNCT'): 2,
        ('S', 'gerundi'): 2,
        ('sentence', 'sp', 'grup.verb', 'S', 'PUNCT'): 2,
        ('S', 'sn', 'morfema.verbal', 'grup.verb', 'sp'): 2,
        ('S', 'grup.verb', 'sn', 'sn'): 2,
        ('S', 'PUNCT', 'sadv', 'participi', 'sp', 'PUNCT'): 2,
        ('grup.nom', 'grup.nom', 'conj', 'S'): 2,
        ('S', 'sp', 'grup.verb', 'sn', 'sp'): 2,
        ('conj', 'ADV'): 2,
        ('sentence', 'PUNCT', 'S', 'conj', 'S', 'PUNCT'): 2,
        ('S', 'participi', 'sp', 'PUNCT'): 2,
        ('sentence', 'PUNCT', 'sadv', 'participi', 'sn', 'PUNCT'): 2,
        ('sentence', 'conj', 'sn', 'grup.verb', 'sp', 'PUNCT'): 2,
        ('s.a', 's.a', 'conj', 'S'): 2,
        ('grup.prep', 'prep', 'S', 'prep'): 2,
        ('grup.nom', 'NOUN', 's.a', 's.a', 'sp'): 2,
        ('S', 'PUNCT', 'conj', 'S', 'conj', 'S'): 2,
        ('S', 'neg', 'morfema.verbal', 'grup.verb', 'sn'): 2,
        ('S', 'grup.verb', 'sn', 'PUNCT'): 2,
        ('grup.nom', 'PRON', 'sp', 'S'): 2,
        ('S', 'sp', 'sn', 'grup.verb', 'sp'): 2,
        ('sn', 'grup.w'): 2,
        ('sadv', 'sp', 'sadv'): 2,
        ('S', 'sn', 'grup.verb', 'S', 'PUNCT'): 2,
        ('S', 'grup.verb', 'sp', 'sp'): 2,
        ('S', 'PUNCT', 'sp', 'morfema.verbal', 'grup.verb', 'sn', 'sp'): 2,
        ('S', 'sadv', 'S'): 2,
        ('sn', 'interjeccio'): 2,
        ('sentence', 'sn', 'neg', 'grup.verb', 'sn', 'sp', 'PUNCT'): 2,
        ('interjeccio', 'NUM'): 2,
        ('sentence', 'sn', 'neg', 'grup.verb', 'S', 'PUNCT'): 2,
        ('sn', 'sn'): 2,
        ('S', 'sn', 'grup.verb', 'sp', 'sn'): 2,
        ('S', 'PUNCT', 'S', 'PUNCT', 'S', 'PUNCT', 'S', 'PUNCT', 'S'): 2,
        ('sn', 'sn', 'sn', 'sp', 'PUNCT'): 2,
        ('S', 'sp', 'sadv'): 2,
        ('s.a', 'sadv', 's.a'): 2,
        ('grup.adv', 'ADV', 'SCONJ'): 2,
        ('S', 'S', 'sn', 'S'): 2,
        ('sentence', 'sn', 'morfema.verbal', 'grup.verb', 'sp', 'sp', 'PUNCT'): 2,
        ('sp', 'PUNCT', 'prep', 'sp'): 2,
        ('sentence', 'neg', 'grup.verb', 'sn', 'sn', 'PUNCT'): 2,
        ('S', 'PUNCT', 'S', 'PUNCT', 'NUM', 'PUNCT'): 2,
        ('S', 'conj', 'grup.verb', 'sp'): 2,
        ('grup.nom', 's.a', 'NOUN', 'sp', 'sp'): 2,
        ('S', 'S', 'PUNCT', 'S', 'PUNCT', 'S', 'PUNCT', 'S'): 2,
        ('S', 'sn', 'infinitiu', 'sp'): 2,
        ('sn', 'sn', 'PUNCT', 'sn', 'PUNCT', 'sn'): 2,
        ('sn', 'sn', 'sn'): 2,
        ('sn', 'sn', 'conj', 'S'): 2,
        ('sentence', 'sp', 'sn', 'grup.verb', 'sadv', 'sn', 'PUNCT'): 2,
        ('S', 'sp', 'neg', 'grup.verb', 'sn'): 2,
        ('S', 'S', 'PUNCT', 'S', 'PUNCT', 'S', 'conj', 'S'): 2,
        ('grup.nom', 'PROPN', 'sp', 'S'): 2,
        ('infinitiu', 'VERB', 'infinitiu'): 2,
        ('S', 'PUNCT', 'sadv', 'participi', 'sn', 'PUNCT'): 2,
        ('grup.nom', 'NOUN', 'SCONJ'): 2,
        ('S', 'conj', 'sn', 'neg', 'grup.verb', 'sn', 'PUNCT'): 2,
        ('grup.prep', 'ADP', 'NOUN', 'ADP'): 2,
        ('S', 'morfema.verbal', 'grup.verb'): 2,
        ('S', 'sadv', 'sn', 'sp'): 2,
        ('sentence', 'sn', 'morfema.verbal', 'grup.verb', 'sn', 'PUNCT'): 2,
        ('sentence', 'sp', 'sn', 'grup.verb', 'sp', 'sp', 'PUNCT'): 2,
        ('sentence', 'PUNCT', 'sn', 'S', 'PUNCT', 'PUNCT'): 2,
        ('grup.nom', 's.a', 'NOUN', 's.a', 'S'): 2,
        ('S', 'S', 'grup.verb', 'sp'): 2,
        ('S', 'S', 'sadv', 'sp'): 2,
        ('S', 'sn', 'sn'): 2,
        ('S', 'sn', 'neg', 'sn', 'grup.verb', 'sn'): 2,
        ('S', 'PUNCT', 'S', 'PUNCT', 'S'): 2,
        ('grup.z', 'NUM', 'PUNCT'): 2,
        ('S', 'conj', 'sn', 'grup.verb', 'sp', 'PUNCT'): 2,
        ('sn', 'sn', 'PUNCT', 'sn', 'PUNCT'): 2,
        ('S', 'infinitiu', 'morfema.pronominal', 'sn', 'PUNCT'): 1,
        ('grup.nom', 'NOUN', 's.a', 'sp', 'PUNCT', 'sp'): 1,
        ('sentence', 'grup.verb', 'sadv', 'sn', 'sp', 'PUNCT'): 1,
        ('sp', 'sp', 'sn'): 1,
        ('sentence', 'sn', 'sadv', 'grup.verb', 'sp', 'sp', 'sn', 'sp', 'PUNCT'): 1,
        ('s.a', 's.a', 'PUNCT', 's.a', 'PUNCT', 's.a', 'PUNCT', 's.a', 'conj', 's.a'): 1,
        ('grup.nom', 'INTJ'): 1,
        ('S', 'PUNCT', 'S', 'PUNCT', 'sn', 'grup.verb', 'sn', 'PUNCT'): 1,
        ('sentence', 'sn', 'grup.verb', 'sp', 'sp', 'sn', 'PUNCT'): 1,
        ('grup.nom', 'grup.nom', 'PUNCT', 'sp'): 1,
        ('sentence', 'grup.verb', 'sp', 'S', 'PUNCT'): 1,
        ('grup.nom', 'PROPN', 's.a', 'sp'): 1,
        ('sentence', 'neg', 'grup.verb', 's.a', 'sp', 'sn', 'PUNCT'): 1,
        ('sentence', 'sn', 'grup.verb', 'sadv', 'PUNCT', 'S', 'PUNCT'): 1,
        ('sp', 'prep', 'PUNCT'): 1,
        ('S', 'PUNCT', 'PUNCT', 'sn', 'grup.verb', 'S'): 1,
        ('grup.nom', 'NOUN', 'sp', 'sadv'): 1,
        ('sentence', 'S', 'sn', 'grup.verb', 'sn', 'PUNCT', 'PUNCT', 'PUNCT'): 1,
        ('S', 'conj', 'neg', 'morfema.verbal', 'grup.verb', 'sn', 'PUNCT'): 1,
        ('grup.verb', 'VERB', 'gerundi'): 1,
        ('sn', 'sn', 'PUNCT', 'sn', 'sp'): 1,
        ('sentence', 'grup.verb', 'S', 'PUNCT'): 1,
        ('sentence', 'sn', 'sp', 'grup.verb', 's.a', 'PUNCT'): 1,
        ('grup.nom', 's.a', 'NOUN', 's.a', 'sp', 'sp'): 1,
        ('S', 'sadv', 'sp', 'grup.verb', 'sn'): 1,
        ('S', 'sn', 'grup.verb', 'sadv', 'participi', 'sp'): 1,
        ('S', 'neg', 'grup.verb', 'PUNCT'): 1,
        ('S', 'grup.verb', 's.a', 'sp'): 1,
        ('S', 'PUNCT', 'sn', 'PUNCT', 'sn', 'PUNCT', 'sn'): 1,
        ('sentence', 'sn', 'PUNCT', 'sn', 'PUNCT'): 1,
        ('grup.nom', 'grup.nom', 'PUNCT', 'S', 'conj', 'S'): 1,
        ('sentence', 'sn', 'PUNCT', 'sn', 'grup.nom', 'PUNCT'): 1,
        ('grup.nom', 'NOUN', 'sp', 'S', 'S'): 1,
        ('grup.nom', 'sn', 'sp', 'S'): 1,
        ('sentence', 'grup.verb', 's.a', 'sp', 'S', 'PUNCT'): 1,
        ('S', 'PUNCT', 'sn', 'sn'): 1,
        ('S', 'relatiu', 'neg', 'sn', 'grup.verb', 'sadv'): 1,
        ('sentence', 'PUNCT', 'S', 'PUNCT', 'sn', 'grup.verb', 'sp', 'PUNCT'): 1,
        ('grup.nom', 'grup.nom', 'sp', 'sp'): 1,
        ('sentence', 'PUNCT', 'sn', 'S', 'PUNCT'): 1,
        ('sentence', 'S', 'grup.verb', 'sn', 'PUNCT'): 1,
        ('grup.verb', 'AUX', 'PUNCT', 'infinitiu'): 1,
        ('sn', 'sn', 'PUNCT', 'S'): 1,
        ('S', 'conj', 'grup.verb', 'S'): 1,
        ('sentence', 'sp', 'morfema.verbal', 'grup.verb', 'sn', 'sp', 'PUNCT'): 1,
        ('S', 'sadv', 'sn', 'grup.verb'): 1,
        ('S', 'PUNCT', 'PUNCT', 'sn', 'grup.verb', 'sp'): 1,
        ('sentence', 'sn', 'grup.verb', 'sadv', 'PUNCT', 'PUNCT', 'PUNCT'): 1,
        ('sentence', 'S', 'PUNCT', 'S', 'PUNCT', 'S', 'conj', 'S', 'PUNCT'): 1,
        ('sentence', 'sn', 'grup.verb', 'sn', 'PUNCT', 'sp', 'PUNCT'): 1,
        ('S', 'relatiu', 'sn', 'grup.verb'): 1,
        ('S', 'neg', 'grup.verb', 'sp', 'PUNCT'): 1,
        ('S', 'participi', 'sp', 'PUNCT', 'S'): 1,
        ('grup.nom', 'SCONJ'): 1,
        ('sentence', 'S', 'neg', 'grup.verb', 'sn', 'PUNCT'): 1,
        ('grup.nom', 'PROPN', 'sn', 'S'): 1,
        ('sp', 'sp', 'conj', 'sadv'): 1,
        ('S', 'PUNCT', 'conj', 'morfema.pronominal', 'grup.verb', 's.a', 'PUNCT'): 1,
        ('sentence', 'neg', 'morfema.verbal', 'grup.verb', 'sp', 'PUNCT'): 1,
        ('sentence', 'conj', 'grup.verb', 'sp', 'PUNCT'): 1,
        ('S', 'infinitiu', 'sn', 'sp', 'sp'): 1,
        ('sentence', 'conj', 'sn', 'grup.verb', 'S', 'PUNCT'): 1,
        ('S', 'PUNCT', 'conj', 'grup.verb', 's.a'): 1,
        ('sentence', 'PUNCT', 'S', 'sadv', 'sn', 'grup.verb', 'S', 'PUNCT'): 1,
        ('S', 'grup.verb', 'sadv'): 1,
        ('sentence', 'sadv', 'grup.verb', 'S', 'PUNCT'): 1,
        ('sentence', 'sp', 'S'): 1,
        ('sn', 'grup.nom', 'spec'): 1,
        ('sentence', 'neg', 'morfema.verbal', 'grup.verb', 'sadv', 'S', 'PUNCT'): 1,
        ('S', 'infinitiu', 'sp', 'sn', 'sn', 'sp', 'S'): 1,
        ('sn', 'spec'): 1,
        ('S', 'gerundi', 'morfema.pronominal', 'sp', 'sp'): 1,
        ('sentence', 'morfema.verbal', 'grup.verb', 'sn', 'sp', 'sp', 'PUNCT'): 1,
        ('sentence', 'grup.verb', 'sadv', 'sn', 'PUNCT'): 1,
        ('sentence', 'S', 'sadv', 'grup.verb', 'sp', 'PUNCT'): 1,
        ('S', 'conj', 'sp', 'morfema.verbal', 'grup.verb', 'sn', 'PUNCT'): 1,
        ('grup.verb', 'AUX', 'infinitiu', 'morfema.pronominal', 'sn'): 1,
        ('sentence', 'S', 'sp', 'PUNCT'): 1,
        ('sentence', 'sp', 'morfema.verbal', 'sn', 'grup.verb', 'sn', 'sp', 'PUNCT'): 1,
        ('S', 'sadv', 'sp', 'sp'): 1,
        ('S', 'infinitiu', 'sp', 'sp', 'sp'): 1,
        ('grup.nom', 'PRON', 's.a'): 1,
        ('S', 'sn', 'grup.verb', 'sp', 'S', 'PUNCT'): 1,
        ('S', 'sp', 'grup.verb', 'sp', 'sp'): 1,
        ('sentence', 'morfema.verbal', 'grup.verb', 'S', 'PUNCT'): 1,
        ('sn', 'PUNCT', 'sn', 'sp', 'PUNCT'): 1,
        ('sentence', 'sp', 'morfema.verbal', 'grup.verb', 'sn', 'PUNCT', 'S', 'conj', 'S', 'PUNCT'): 1,
        ('sn', 'grup.z', 'grup.nom'): 1,
        ('grup.z', 'NUM', 'conj', 'spec'): 1,
        ('S', 'sp', 'grup.verb', 'S'): 1,
        ('S', 'sp', 'grup.verb', 'sp', 'S'): 1,
        ('sn', 'grup.pron'): 1,
        ('grup.pron', 'DET', 'DET'): 1,
        ('S', 'conj', 'neg', 'grup.verb', 'sp'): 1,
        ('sentence', 'sp', 'neg', 'grup.verb', 's.a', 'S', 'PUNCT'): 1,
        ('sentence', 'conj', 'sn', 'morfema.verbal', 'grup.verb', 'S', 'PUNCT'): 1,
        ('S', 'sadv', 'infinitiu', 'sadv'): 1,
        ('sadv', 'sn', 'sadv'): 1,
        ('sentence', 'sp', 'grup.verb', 'sn', 'sp', 'S', 'PUNCT'): 1,
        ('sentence', 'grup.verb', 'S', 'sn', 'S', 'PUNCT'): 1,
        ('grup.nom', 'NOUN', 'PUNCT', 'S'): 1,
        ('sentence', 'grup.verb', 'sp', 'sn', 'PUNCT'): 1,
        ('sentence', 'PUNCT', 'PUNCT', 'sadv', 'participi', 'sp', 'PUNCT'): 1,
        ('sentence', 'grup.verb', 'sn', 'sp', 'PUNCT'): 1,
        ('sentence', 'sn', 'grup.verb', 'sn', 'sp', 'S', 'PUNCT'): 1,
        ('grup.nom', 'S', 'NOUN', 'sp'): 1,
        ('grup.nom', 'grup.nom', 'PUNCT', 'grup.nom', 'PUNCT', 'grup.nom', 'PUNCT', 'grup.nom', 'conj', 'grup.nom'): 1,
        ('sentence', 'PUNCT', 'sadv', 'participi', 'sn', 'sp', 'PUNCT', 'S', 'S'): 1,
        ('S', 'PUNCT', 'S', 'PUNCT'): 1,
        ('sentence', 'sadv', 'grup.verb', 'sn', 'sn', 'PUNCT'): 1,
        ('sentence', 'PUNCT', 'sadv', 'participi', 'sp', 'PUNCT', 'grup.nom', 'PUNCT'): 1,
        ('grup.nom', 'PUNCT', 'grup.nom', 'PUNCT'): 1,
        ('S', 'participi', 'sadv', 'sn'): 1,
        ('sentence', 'sn', 'grup.verb', 'sadv', 's.a', 'sp', 'PUNCT'): 1,
        ('spec', 'DET', 'PRON'): 1,
        ('grup.nom', 'grup.z', 'sadv', 'sp'): 1,
        ('sentence', 'sadv', 'sn', 'neg', 'morfema.verbal', 'grup.verb', 'sp', 'PUNCT'): 1,
        ('S', 'sn', 'grup.verb', 'sn', 'sadv', 'PUNCT'): 1,
        ('grup.nom', 'NOUN', 's.a', 'S', 'S'): 1,
        ('spec', 'ADV', 'ADP', 'NUM'): 1,
        ('sn', 'conj', 'sn', 'conj', 'sn'): 1,
        ('sentence', 'grup.verb', 'S', 'sp', 'S', 'PUNCT'): 1,
        ('grup.nom', 'NOUN', 'sp', 'sp', 'sp', 'sp', 'sp'): 1,
        ('sentence', 'grup.verb', 'sn', 'sn', 'PUNCT'): 1,
        ('S', 'conj', 'neg', 'morfema.pronominal', 'grup.verb', 'S'): 1,
        ('sentence', 'sadv', 'grup.verb', 'sn', 'sp', 'PUNCT'): 1,
        ('grup.nom', 'sn', 'sp'): 1,
        ('sentence', 'sp', 'grup.verb', 'sp', 'PUNCT'): 1,
        ('S', 'sn', 'grup.verb', 'S', 'sn', 'PUNCT'): 1,
        ('S', 'PUNCT', 'conj', 'neg', 'grup.verb', 'sn', 'PUNCT'): 1,
        ('S', 'sn', 'neg', 'grup.verb', 'sn'): 1,
        ('S', 'grup.verb', 'S', 'sadv', 'sp', 'PUNCT'): 1,
        ('grup.nom', 'grup.nom', 'sn', 'grup.nom'): 1,
        ('grup.nom', 'NOUN', 's.a', 'S', 'sn'): 1,
        ('S', 'sp', 's.a'): 1,
        ('sentence', 'sp', 'sn', 'neg', 'grup.verb', 's.a', 'sp', 'sp', 'PUNCT'): 1,
        ('grup.nom', 'NOUN', 's.a', 'sn'): 1,
        ('grup.nom', 'grup.z', 'sn', 's.a', 'sp'): 1,
        ('sn', 'S', 'sn'): 1,
        ('S', 'PUNCT', 'grup.nom', 'sn', 'grup.verb', 's.a', 'sp'): 1,
        ('grup.nom', 'PROPN', 'PROPN', 'PUNCT'): 1,
        ('sentence', 'sadv', 'sp', 'sn', 'grup.verb', 's.a', 'PUNCT'): 1,
        ('s.a', 's.a', 'S'): 1,
        ('sentence', 'sn', 'PUNCT', 'sn', 'grup.verb', 'sadv', 'sp', 'PUNCT'): 1,
        ('sentence', 'S', 'sn', 'morfema.verbal', 'grup.verb', 'sp', 'PUNCT'): 1,
        ('S', 'conj', 'sn', 'neg', 'morfema.pronominal', 'grup.verb', 'sp', 'PUNCT'): 1,
        ('sentence', 'PUNCT', 'PUNCT', 'sn', 'S', 'PUNCT'): 1,
        ('S', 'PUNCT', 'sp', 'sn', 'grup.verb', 'sp', 'sn', 'sp'): 1,
        ('sentence', 'morfema.verbal', 'grup.verb', 'sp', 'sp', 'PUNCT'): 1,
        ('S', 'conj', 'sadv', 'S', 'sn'): 1,
        ('sadv', 'grup.adv', 'S'): 1,
        ('grup.nom', 'NOUN', 'sp', 's.a', 's.a', 'sp'): 1,
        ('sentence', 'sn', 'grup.verb', 'sp', 'sp', 'conj', 'S', 'PUNCT'): 1,
        ('sp', 'sp', 'PUNCT', 'sp', 'PUNCT', 'sp', 'conj', 'sp'): 1,
        ('sentence', 'sadv', 'grup.verb', 'sp', 'PUNCT'): 1,
        ('S', 'sn', 'conj', 'S', 'sp', 'sp'): 1,
        ('S', 'PUNCT', 'conj', 'neg', 'morfema.verbal', 'grup.verb', 'sadv', 'sn'): 1,
        ('S', 'PUNCT', 'grup.verb', 'sn'): 1,
        ('grup.verb', 'gerundi', 'sp'): 1,
        ('sentence', 'sn', 'grup.verb', 'sp', 'sn', 'sp', 'conj', 'S', 'PUNCT'): 1,
        ('sp', 'PUNCT', 'sadv', 'infinitiu', 'PUNCT'): 1,
        ('sn', 'PUNCT', 'conj', 'sn', 'conj', 'sn'): 1,
        ('sentence', 'sn', 'sp', 'grup.verb', 'sp', 'PUNCT'): 1,
        ('sentence', 'sn', 'PUNCT', 'sp', 'sn', 'morfema.verbal', 'grup.verb', 'sp', 'S', 'PUNCT'): 1,
        ('S', 'PUNCT', 'S', 'PUNCT', 'S', 'PUNCT', 'S', 'conj', 'S'): 1,
        ('sentence', 'sp', 'sn', 'grup.verb', 'sadv', 'sp', 'PUNCT'): 1,
        ('S', 'PUNCT', 'S', 'PUNCT', 'S', 'conj', 'S', 'PUNCT', 'conj', 'S'): 1,
        ('sentence', 'S', 'S', 'conj', 'S', 'PUNCT'): 1,
        ('sentence', 'S', 'inc', 'sp', 'PUNCT', 'sn', 'PUNCT'): 1,
        ('S', 'sn', 'sadv', 'morfema.verbal', 'grup.verb'): 1,
        ('sentence', 'sp', 'PUNCT'): 1,
        ('grup.nom', 'PROPN', 'NUM', 'DET', 'grup.nom'): 1,
        ('S', 'morfema.verbal', 'grup.verb', 'sp', 'sp', 'sp'): 1,
        ('S', 'sadv'): 1,
        ('sentence', 'PUNCT', 'PUNCT', 'PUNCT', 'PUNCT', 'grup.verb', 'sn', 'PUNCT', 'sn', 'PUNCT'): 1,
        ('sentence', 'PUNCT', 'PUNCT', 'PUNCT', 'PUNCT', 'sn', 'S', 'PUNCT', 'PUNCT'): 1,
        ('S', 'PUNCT', 'sp', 'sn', 'grup.verb', 'sn', 'sp', 'PROPN'): 1,
        ('sentence', 'sp', 'sn', 'morfema.verbal', 'grup.verb', 'sp', 'PUNCT', 'PUNCT'): 1,
        ('sentence', 'sadv', 'sp', 'morfema.verbal', 'grup.verb', 'sn'): 1,
        ('sentence', 'PUNCT', 'sp', 'sn', 'grup.verb', 'sn', 'sp', 'PUNCT'): 1,
        ('sentence', 'grup.nom', 'S', 'PUNCT'): 1,
        ('grup.nom', 'S', 'sn'): 1,
        ('S', 'PUNCT', 'sp', 'sn', 'grup.verb', 'sn', 'sp'): 1,
        ('sentence', 'sadv', 'morfema.verbal', 'grup.verb', 'S', 'PUNCT'): 1,
        ('S', 'conj', 'sn', 'neg', 'grup.verb', 'S', 'PUNCT', 'PUNCT'): 1,
        ('conj', 'SCONJ', 'PUNCT'): 1,
        ('S', 'conj', 'sn', 'grup.verb', 'sn', 'S'): 1,
        ('S', 'PUNCT', 'sn', 'S', 'sp', 'grup.verb', 'sn', 'PUNCT'): 1,
        ('S', 'PUNCT', 'S', 'PUNCT', 'PROPN', 'PUNCT', 'SYM', 'PUNCT'): 1,
        ('S', 'sp', 'sn', 'grup.verb', 'sn', 'sp'): 1,
        ('S', 'conj', 'sn', 'sn', 'grup.verb', 'sn', 'sp'): 1,
        ('sn', 'PUNCT', 'spec', 'grup.nom'): 1,
        ('grup.nom', 'NOUN', 's.a', 'S', 'S', 'PUNCT', 'sp', 'PUNCT', 'conj', 'S'): 1,
        ('sentence', 'S', 'morfema.verbal', 'grup.verb', 'sp', 'PUNCT'): 1,
        ('sentence', 'sn', 'sn', 'grup.verb', 's.a', 'PUNCT'): 1,
        ('grup.a', 'ADJ', 'sp', 'sp'): 1,
        ('grup.nom', 'NOUN', 'sp', 'sp', 'S'): 1,
        ('S', 'sn', 'sadv', 'morfema.verbal', 'grup.verb', 'sp'): 1,
        ('grup.nom', 'S', 'sp'): 1,
        ('S', 'PUNCT', 'gerundi', 'sn'): 1,
        ('sentence', 'sadv', 'sp', 'neg', 'morfema.verbal', 'grup.verb', 'sn', 'PUNCT'): 1,
        ('sp', 'PUNCT', 'prep', 'S', 'PUNCT'): 1,
        ('sentence', 'grup.z', 'PUNCT', 'S', 'sadv', 'grup.verb', 'sp', 'S', 'PUNCT'): 1,
        ('grup.z', 'NUM'): 1,
        ('S', 'sn', 'sadv', 'grup.verb', 'sn', 'sp'): 1,
        ('spec', 'spec', 'conj', 'spec'): 1,
        ('S', 'conj', 'grup.verb', 'sn', 'sp'): 1,
        ('S', 'neg', 'infinitiu', 'sn', 'sp'): 1,
        ('grup.nom', 'S', 'grup.z', 'sp'): 1,
        ('sentence', 'sn', 'morfema.verbal', 'grup.verb', 'S', 'PUNCT'): 1,
        ('sentence', 'sn', 'sadv', 'grup.verb', 'sp', 'PUNCT', 'PUNCT'): 1,
        ('sentence', 'sadv', 'sn', 'neg', 'grup.verb', 'sp', 'sn', 'PUNCT'): 1,
        ('grup.nom', 'NUM', 's.a'): 1,
        ('grup.verb', 'AUX', 'sadv', 'infinitiu'): 1,
        ('S', 'PUNCT', 'conj', 'sn', 'morfema.pronominal', 'grup.verb', 'sp', 'sp'): 1,
        ('sentence', 'sn', 'grup.verb', 's.a', 'sadv', 'PUNCT'): 1,
        ('sentence', 'PUNCT', 'sadv', 'participi', 'sp', 'PUNCT', 'sn'): 1,
        ('grup.w', 'PROPN', 'NUM'): 1,
        ('S', 'participi', 'sadv', 'sp'): 1,
        ('sn', 'S', 'sn', 'grup.verb', 'sp', 'sp', 'PUNCT'): 1,
        ('S', 'PUNCT', 'sadv', 'participi', 'sn', 'PUNCT', 'S', 'PUNCT'): 1,
        ('S', 'sadv', 'conj', 'sadv'): 1,
        ('sentence', 'PUNCT', 'S', 'PUNCT', 'S', 'PUNCT'): 1,
        ('S', 'PUNCT', 'inc', 'S', 'conj', 'S'): 1,
        ('S', 'sadv', 'participi', 'sn', 'sp', 'PUNCT'): 1,
        ('S', 'sp', 'PUNCT'): 1,
        ('sentence', 'S', 'PUNCT', 'sn', 'grup.verb', 'S', 'PUNCT', 'PUNCT'): 1,
        ('S', 'PUNCT', 'sadv', 'participi', 'sp', 'sp', 'PUNCT'): 1,
        ('S', 'PUNCT', 'S', 'PUNCT', 'S', 'PUNCT', 'grup.verb', 'sn'): 1,
        ('S', 'sn', 'morfema.verbal', 'grup.verb', 'sadv'): 1,
        ('S', 'sp', 'sn', 'sp'): 1,
        ('sentence', 'S', 'conj', 'S', 'PUNCT', 'sp', 'PUNCT'): 1,
        ('sentence', 'conj', 'PUNCT', 'S', 'sn', 'grup.verb', 'sp', 'PUNCT', 'inc', 'S', 'PUNCT'): 1,
        ('grup.verb', 'PRON'): 1,
        ('S', 'grup.verb', 'sp', 'sp', 'sp'): 1,
        ('sentence', 'S', 'grup.verb', 'sadv', 'sn', 'S', 'PUNCT'): 1,
        ('S', 'conj', 'grup.verb', 'S', 'PUNCT'): 1,
        ('grup.nom', 'NOUN', 'ADP', 'SCONJ'): 1,
        ('sentence', 'sn', 'sn', 'grup.verb', 'sn', 'sp', 'PUNCT', 'inc', 'S', 'PUNCT'): 1,
        ('S', 'S', 'PUNCT', 'S', 'PUNCT', 'S', 'PUNCT', 'S', 'conj', 'S', 'PUNCT'): 1,
        ('S', 'neg', 'grup.verb', 'sp', 'sp'): 1,
        ('sentence', 'sn', 'grup.verb', 's.a', 'sn', 'PUNCT'): 1,
        ('sn', 'S', 'conj', 'sn', 'PUNCT', 'sp'): 1,
        ('grup.nom', 'grup.z', 'sn', 'sp'): 1,
        ('sentence', 'PUNCT', 'S', 'S', 'PUNCT', 'S', 'PUNCT'): 1,
        ('grup.nom', 'NOUN', 'sn', 's.a'): 1,
        ('grup.adv', 'PRON', 'ADV'): 1,
        ('S', 'infinitiu', 'morfema.pronominal', 'sn', 'sadv'): 1,
        ('S', 'S', 'conj', 'sp', 'PUNCT'): 1,
        ('sentence', 'sp', 'sn', 'sn', 'grup.verb', 'S', 'PUNCT'): 1,
        ('sentence', 'inc', 'sn', 'PUNCT'): 1,
        ('interjeccio', 'X', 'PUNCT', 'PUNCT', 'NUM', 'PUNCT'): 1,
        ('sentence', 'PUNCT', 'sn', 'sn', 'PUNCT'): 1,
        ('sentence', 'S', 'PUNCT', 'inc', 'S', 'PUNCT'): 1,
        ('inc', 'PUNCT', 'PUNCT', 'PUNCT'): 1,
        ('S', 'PUNCT', 'sn', 'PUNCT', 'sn', 'grup.verb', 'S', 'inc', 'S', 'PUNCT', 'S'): 1,
        ('grup.nom', 'NOUN', 'sn', 'sp', 'S'): 1,
        ('sn', 'interjeccio', 'PUNCT'): 1,
        ('sentence', 'sn', 'neg', 'grup.verb', 'conj', 'S', 'PUNCT'): 1,
        ('sentence', 'sn', 'sadv', 'grup.verb', 'sn', 'PUNCT'): 1,
        ('grup.nom', 'grup.nom', 'PUNCT', 'grup.nom', 'PUNCT', 'grup.nom', 'conj', 'grup.nom'): 1,
        ('sentence', 'sn', 'morfema.pronominal', 'grup.verb', 'sp', 'PUNCT'): 1,
        ('sn', 'grup.nom', 'conj', 'grup.nom'): 1,
        ('sentence', 'S', 'sn', 'grup.verb', 'sp', 'sn', 'sp', 'PUNCT'): 1,
        ('grup.cs', 'DET', 'NOUN', 'SCONJ'): 1,
        ('S', 'neg', 'grup.verb', 'sn', 'sp'): 1,
        ('grup.nom', 'VERB'): 1,
        ('S', 'sn', 'conj', 'S'): 1,
        ('sentence', 'S', 'sn', 'PUNCT'): 1,
        ('S', 'neg', 'grup.verb', 'sn', 'PUNCT'): 1,
        ('sn', 'PUNCT', 'sn', 'sn', 'sn'): 1,
        ('sn', 'sn', 'conj', 'S', 'PUNCT'): 1,
        ('S', 'relatiu', 'sn', 'grup.verb', 'sp', 'sp'): 1,
        ('sn', 'inc', 'sn', 'PUNCT', 'sn', 'PUNCT', 'S'): 1,
        ('S', 'inc', 'S', 'PUNCT', 'sn'): 1,
        ('inc', 'inc', 'sn'): 1,
        ('sn', 'sn', 'sp', 'PUNCT'): 1,
        ('conj', 'PUNCT'): 1,
        ('sn', 'sn', 'sn', 'PUNCT', 's.a', 'PUNCT', 'sn', 'PUNCT', 'sn', 'PUNCT', 'sn'): 1,
        ('grup.nom', 'NOUN', 'sp', 'sp', 'sadv'): 1,
        ('sentence', 'sn', 'neg', 'grup.verb', 's.a', 'PUNCT'): 1,
        ('sentence', 'sp', 'neg', 'grup.verb', 'sp', 'PUNCT', 'sp', 'conj', 'S', 'PUNCT'): 1,
        ('sentence', 'sp', 'sp', 'S', 'PUNCT'): 1,
        ('grup.nom', 's.a', 'grup.nom'): 1,
        ('S', 'neg', 'grup.verb', 'sp', 'sp', 'PUNCT'): 1,
        ('S', 'conj', 'sadv', 'grup.verb', 'sp'): 1,
        ('sentence', 'sn', 'neg', 'grup.verb', 'sn', 'sp', 'PUNCT', 'conj', 'S', 'PUNCT'): 1,
        ('grup.verb', 'NOUN'): 1,
        ('S', 'sadv', 'sn', 'grup.verb', 'sp', 'S', 'PUNCT'): 1,
        ('sentence', 'sp', 'morfema.verbal', 'grup.verb', 'sp', 'sp', 'PUNCT'): 1,
        ('S', 'sn', 'neg', 'grup.verb', 's.a', 'PUNCT'): 1,
        ('s.a', 'PUNCT', 'conj', 's.a', 'PUNCT', 'conj', 'sp', 'PUNCT', 'sn', 'PUNCT', 'conj', 'S'): 1,
        ('s.a', 'grup.a', 'conj', 'grup.adv'): 1,
        ('sn', 'grup.nom', 'grup.nom'): 1,
        ('S', 'conj', 'sp', 'sn', 'grup.verb', 'sp'): 1,
        ('sentence', 'PUNCT', 'sadv', 'participi', 'sp', 'PUNCT', 'PUNCT', 'grup.nom', 'PUNCT', 'PUNCT'): 1,
        ('sp', 'conj', 'sp', 'conj', 'sp', 'PUNCT'): 1,
        ('sentence', 'sn', 'grup.verb', 'sn', 'sp', 'PUNCT', 'conj', 'S', 'PUNCT'): 1,
        ('S', 'sn', 'morfema.pronominal', 'grup.verb', 'sn', 'sn', 'S', 'PUNCT'): 1,
        ('S', 'PUNCT', 'grup.adv', 'neg', 'grup.verb'): 1,
        ('S', 'PUNCT', 'participi', 'sp'): 1,
        ('S', 'S', 'neg', 'grup.verb', 'sp', 'PUNCT'): 1,
        ('S', 'conj', 'sp', 'grup.verb', 's.a', 'S'): 1,
        ('S', 'conj', 'S'): 1,
        ('S', 'conj', 'grup.verb'): 1,
        ('S', 'conj', 'sp', 'morfema.verbal', 'grup.verb', 'S'): 1,
        ('S', 'conj', 'grup.verb', 's.a', 'sp'): 1,
        ('sentence', 'sp', 'neg', 'morfema.verbal', 'grup.verb', 'sp', 'S', 'PUNCT'): 1,
        ('S', 'sp', 'grup.verb', 'sadv', 'sp'): 1,
        ('S', 'PUNCT', 'sn', 'S'): 1,
        ('S', 'S', 'PUNCT', 'S', 'PUNCT', 'S', 'conj', 'S', 'PUNCT', 'S', 'PUNCT', 'S', 'PUNCT'): 1,
        ('S', 'conj', 'sadv', 'sn', 'grup.verb'): 1,
        ('sentence', 'S', 'S', 'PUNCT', 'S', 'PUNCT', 'S', 'PUNCT'): 1,
        ('S', 'infinitiu', 'conj', 'S'): 1,
        ('sn', 'sn', 's.a', 'S'): 1,
        ('sp', 'sp', 'PUNCT', 'sp', 'conj', 'sp'): 1,
        ('S', 'sp', 'conj', 'sp', 'PUNCT', 'S'): 1,
        ('S', 'sn', 'sadv', 'grup.verb', 'sn'): 1,
        ('sentence', 'grup.verb', 'sp', 'sp', 'PUNCT'): 1,
        ('grup.verb', 'AUX', 'sadv', 'grup.verb'): 1,
        ('sentence', 'S', 'PUNCT', 'S', 'PUNCT', 'S', 'PUNCT', 'S', 'PUNCT'): 1,
        ('S', 'PUNCT', 'gerundi', 'sp', 'S'): 1,
        ('S', 'conj', 'S', 'sn', 'sp', 'PUNCT', 'S'): 1,
        ('S', 'gerundi', 'sn', 'sp', 'sp', 'sp'): 1,
        ('S', 'sn', 'S', 'S'): 1,
        ('S', 'neg', 'grup.verb', 'sadv', 'sp'): 1,
        ('S', 'sp', 'sn', 'PUNCT', 'sn', 'PUNCT'): 1,
        ('sp', 'PUNCT', 'prep', 'PUNCT'): 1,
        ('sentence', 'sn', 'sadv', 'grup.verb', 'sp', 'sp', 'PUNCT'): 1,
        ('sn', 'sn', 'PUNCT', 'grup.nom', 'conj', 'grup.nom', 'PUNCT'): 1,
        ('grup.nom', 'NOUN', 'PUNCT'): 1,
        ('sp', 'PUNCT', 'prep', 'sn', 'conj', 'sp'): 1,
        ('sn', 'sn', 'inc'): 1,
        ('S', 'PUNCT', 'sn', 'S', 'neg', 'grup.verb', 'PUNCT', 'S', 'PUNCT'): 1,
        ('S', 'S', 'conj', 'S', 'PUNCT', 's.a', 'conj', 'sadv'): 1,
        ('sentence', 'sp', 'grup.verb', 's.a', 'S', 'PUNCT'): 1,
        ('sentence', 'sn', 'S', 'S', 'PUNCT'): 1,
        ('sn', 'S'): 1,
        ('S', 'S', 'conj', 'sp', 'PUNCT', 'inc'): 1,
        ('sn', 'sn', 'PUNCT', 'sn', 'PUNCT', 'S', 'conj', 'S', 'PUNCT', 'S'): 1,
        ('S', 'gerundi', 'sn', 'sn', 'sp'): 1,
        ('S', 'sadv', 'infinitiu', 'sn'): 1,
        ('S', 'sn', 'infinitiu', 'sp', 'sp', 'S'): 1,
        ('S', 'sadv', 'sn'): 1,
        ('grup.adv', 'PROPN'): 1,
        ('S', 'infinitiu', 'sp', 'sp', 'inc', 'S'): 1,
        ('inc', 'sp'): 1,
        ('sp', 'PUNCT', 'grup.prep', 'PUNCT', 'sn', 'PUNCT'): 1,
        ('grup.prep', 'prep', 'sn'): 1,
        ('S', 'S', 'conj', 'sp'): 1,
        ('sp', 'sadv', 'sp', 'S', 'S'): 1,
        ('sadv', 'sadv', 'PUNCT'): 1,
        ('S', 'PUNCT', 'conj', 'sp', 'grup.verb', 's.a'): 1,
        ('sentence', 'morfema.verbal', 'grup.verb', 'sp', 'PUNCT'): 1,
        ('sp', 'sp', 'PUNCT', 'sn', 'conj', 'S'): 1,
        ('S', 'relatiu', 'morfema.verbal', 'grup.verb', 'sp'): 1,
        ('sentence', 'grup.verb', 'S', 'S', 'PUNCT'): 1,
        ('grup.nom', 'PROPN', 'NUM', 'PROPN', 'sp'): 1,
        ('sentence', 'sp', 'sn', 'sn', 'grup.verb', 'sp', 'PUNCT'): 1,
        ('sp', 'sp', 'PUNCT', 'sp', 'PUNCT', 'sp', 'conj', 'sp', 'PUNCT', 'sp', 'S'): 1,
        ('sp', 'sp', 'sp'): 1,
        ('S', 'PUNCT', 'conj', 'sn', 'grup.verb', 'sp'): 1,
        ('sentence', 'sn', 'grup.verb', 'sadv', 'sp', 'sp', 'PUNCT'): 1,
        ('sentence', 'PUNCT', 'sadv', 'participi', 'sp', 'PUNCT', 'sp', 'PUNCT'): 1,
        ('sentence', 'S', 'conj', 'PUNCT'): 1,
        ('S', 'sp', 'sn', 'grup.verb', 'sn'): 1,
        ('conj', 'PUNCT', 'sadv', 'grup.verb', 'sp', 'sp'): 1,
        ('S', 'grup.verb', 'sadv', 'sn'): 1,
        ('grup.adv', 'ADP', 'NOUN'): 1,
        ('sentence', 'conj', 'sn', 'grup.verb', 'sp', 'sn', 'PUNCT'): 1,
        ('sentence', 'neg', 'grup.verb', 'sn', 'S', 'PUNCT'): 1,
        ('sp', 'sp', 'PUNCT', 'sp', 'conj', 'sp', 'PUNCT', 'sp', 'PUNCT', 'sp', 'sp', 'conj', 'sp'): 1,
        ('S', 'PUNCT', 'conj', 'sn', 'grup.verb', 'sadv', 'sn'): 1,
        ('sp', 'sp', 'conj', 'sn'): 1,
        ('sentence', 'sn', 'neg', 'grup.verb', 'sp', 'sn', 'S', 'PUNCT'): 1,
        ('sentence', 'neg', 'grup.verb', 'sn', 'sp', 'PUNCT'): 1,
        ('S', 'sadv', 'sn', 'grup.verb', 'S'): 1,
        ('S', 'grup.verb', 's.a', 'S'): 1,
        ('S', 'infinitiu', 'sn', 'sn'): 1,
        ('sentence', 'S', 'neg', 'S', 'PUNCT'): 1,
        ('S', 'conj', 'neg', 'sn', 'grup.verb', 'sp'): 1,
        ('S', 'grup.verb', 'conj', 'S'): 1,
        ('grup.verb', 'AUX', 'sn', 'infinitiu'): 1,
        ('infinitiu', 'VERB', 'ADP', 'infinitiu', 'sn'): 1,
        ('S', 'participi', 'sn', 'sp'): 1,
        ('S', 'sn', 'sn', 'grup.verb'): 1,
        ('S', 'morfema.pronominal', 'grup.verb', 'sp'): 1,
        ('sentence', 'S', 'morfema.verbal', 'grup.verb', 'sn', 'sp', 'PUNCT'): 1,
        ('S', 'neg', 'infinitiu', 'morfema.pronominal', 'sn', 'sp'): 1,
        ('sentence', 'S', 'sn', 'grup.verb', 'sn', 'sp', 'sp', 'PUNCT'): 1,
        ('S', 'conj', 'sn', 'morfema.verbal', 'grup.verb', 'sp', 'PUNCT'): 1,
        ('S', 'conj', 'grup.verb', 'sn', 'sadv'): 1,
        ('S', 'morfema.verbal', 'grup.verb', 'sp', 'sn'): 1,
        ('sentence', 'sn', 'morfema.verbal', 'grup.verb', 'sp', 'S', 'PUNCT'): 1,
        ('S', 'PUNCT', 'conj', 'sn', 'grup.verb', 'S'): 1,
        ('S', 'conj', 'neg', 'grup.verb', 'sn'): 1,
        ('S', 'sp', 'PUNCT', 'sn', 'sadv'): 1,
        ('sentence', 'sn', 'grup.verb', 's.a', 'S', 'PUNCT'): 1,
        ('S', 'PUNCT', 'conj', 'sn', 'neg', 'grup.verb', 'sn'): 1,
        ('S', 'sn', 'neg', 'grup.verb', 's.a'): 1,
        ('s.a', 's.a', 'conj', 'sp'): 1,
        ('s.a', 's.a', 'conj', 's.a'): 1,
        ('sentence', 'sp', 'sn', 'grup.verb', 'conj', 'S', 'PUNCT'): 1,
        ('sp', 'prep', 'sn', 'prep', 'sn', 'PUNCT'): 1,
        ('sentence', 'sn', 'sn', 'grup.verb', 'sp', 'sn', 'sp', 'PUNCT'): 1,
        ('S', 'infinitiu', 's.a'): 1,
        ('sn', 'grup.nom', 'PUNCT', 'S'): 1,
        ('grup.nom', 'grup.nom', 'PUNCT', 'sn', 'PUNCT', 'sn', 'conj', 'sn', 'conj', 'S'): 1,
        ('sentence', 'PUNCT', 'sn', 'sn', 'PUNCT', 'sn', 'PUNCT'): 1,
        ('sn', 'sn', 'PUNCT', 'sn', 'PUNCT', 'sn', 'PUNCT', 'sn', 'conj', 'sn'): 1,
        ('grup.nom', 's.a', 'grup.w', 'sp'): 1,
        ('sentence', 'S', 'grup.verb', 'sn', 'sn', 'PUNCT'): 1,
        ('S', 'PUNCT', 'sp', 'sp', 'morfema.verbal', 'grup.verb', 'sn', 'sp'): 1,
        ('S', 'sn', 'grup.verb', 'sn', 'sn', 'PUNCT'): 1,
        ('grup.w', 'NOUN', 'NUM', 'sp'): 1,
        ('S', 'S', 'sn', 'grup.verb', 'sp'): 1,
        ('S', 'conj', 'neg', 'grup.verb', 'sp', 'PUNCT'): 1,
        ('sentence', 'sn', 'grup.verb', 'sadv', 'PUNCT'): 1,
        ('sadv', 'sadv', 'conj', 'sp'): 1,
        ('sentence', 'sn', 'grup.verb', 'sp', 'sp', 'sp', 'PUNCT'): 1,
        ('sentence', 'S', 'morfema.verbal', 'grup.verb', 'sn', 'sn', 'sp', 'S', 'PUNCT'): 1,
        ('grup.nom', 's.a', 'grup.w'): 1,
        ('S', 'PUNCT', 'gerundi', 'S', 'sn'): 1,
        ('sentence', 'S', 'morfema.verbal', 'grup.verb', 'sp', 'sp', 'sp', 'sp', 'PUNCT'): 1,
        ('S', 'conj', 'sp', 'sn', 'grup.verb', 'sp', 'PUNCT'): 1,
        ('S', 'neg', 'grup.verb', 'sn', 'sn', 'PUNCT'): 1,
        ('sentence', 'sn', 'neg', 'grup.verb', 'sp'): 1,
        ('infinitiu', 'AUX', 'grup.verb'): 1,
        ('grup.verb', 'VERB', 'sp'): 1,
        ('grup.nom', 'grup.z', 'sp'): 1,
        ('S', 'S', 'PUNCT', 'S', 'PUNCT', 'S', 'PUNCT', 'S', 'PUNCT', 'S'): 1,
        ('sp', 'sp', 'PUNCT', 'sp', 'conj', 'sp', 'sn', 'PUNCT', 'S'): 1,
        ('grup.nom', 'PRON', 'S', 'sp'): 1,
        ('S', 'S', 'PUNCT', 'sp', 'PUNCT', 'S'): 1,
        ('S', 'sn', 'sp', 'sp'): 1,
        ('sp', 'sp', 'sp', 'sp'): 1,
        ('sentence', 'S', 'morfema.verbal', 'grup.verb', 'sp', 'sn', 'PUNCT'): 1,
        ('sentence', 'S', 'sn', 'grup.verb', 'sp', 'sp', 'PUNCT'): 1,
        ('S', 'conj', 'sp', 'neg', 'grup.verb', 'sn', 'S', 'PUNCT'): 1,
        ('S', 'infinitiu', 'morfema.pronominal'): 1,
        ('grup.nom', 'sp', 'sp'): 1,
        ('S', 'S', 'PUNCT', 'S', 'PUNCT', 'S', 'PUNCT', 'S', 'PUNCT', 'S', 'PUNCT', 'S'): 1,
        ('S', 'sn', 'infinitiu', 'sn', 'sp'): 1,
        ('S', 'S', 'sp', 'sn', 'sp'): 1,
        ('S', 'infinitiu', 'sn', 'S', 'S'): 1,
        ('S', 'conj', 'participi', 'sp'): 1,
        ('grup.cs', 'DET', 'NOUN'): 1,
        ('S', 'PUNCT', 'conj', 'sn', 'sn', 'grup.verb', 'sn'): 1,
        ('S', 'PUNCT', 'S', 'PUNCT', 'S', 'PUNCT', 'S', 'PUNCT', 'S', 'PUNCT', 'S', 'PUNCT', 'S', 'PUNCT'): 1,
        ('sp', 'sp', 'conj', 'S'): 1,
        ('sp', 'conj', 'sp'): 1,
        ('conj', 'grup.adv'): 1,
        ('S', 'S', 'sp', 'sp'): 1,
        ('S', 'S', 'PUNCT', 'S', 'PUNCT', 'S', 'PUNCT', 'sn', 'S', 'conj', 'S', 'PUNCT', 'S', 'PUNCT'): 1,
        ('S', 'infinitiu', 'sp', 'sn', 'sp'): 1,
        ('S', 'infinitiu', 'sn', 'sp', 'S'): 1,
        ('sn', 'PUNCT', 'sn', 'PUNCT', 'sp', 'morfema.verbal', 'grup.verb', 'sn', 'sp', 'PUNCT', 'PUNCT'): 1,
        ('S', 'neg', 'morfema.verbal', 'grup.verb', 'inc', 'sp'): 1,
        ('grup.nom', 'NOUN', 'sn', 'S'): 1,
        ('sentence', 'PUNCT', 'sadv', 'participi', 'sn', 'sp', 'PUNCT', 'S', 'PUNCT'): 1,
        ('sentence', 'morfema.verbal', 'grup.verb', 'sp', 'sn', 'PUNCT'): 1,
        ('spec', 'NUM', 'conj', 'ADV'): 1,
        ('S', 'sn', 'conj', 'S', 'PUNCT', 'S', 'PUNCT', 'S', 'PUNCT', 'S'): 1,
        ('S', 'sn', 'sadv', 'sp'): 1,
        ('S', 'sn', 'grup.verb', 's.a', 'PUNCT'): 1,
        ('sentence', 'grup.verb', 's.a', 'sp', 'sn', 'sadv', 'PUNCT'): 1,
        ('sentence', 'sn', 'grup.verb', 'sp', 'sn', 'sadv', 'sn', 'PUNCT'): 1,
        ('spec', 'DET', 'ADJ', 'NUM'): 1,
        ('sp', 'PUNCT', 'sp', 'conj', 'sp', 'PUNCT'): 1,
        ('S', 'conj', 'sn', 'sadv', 'sn', 'grup.verb'): 1,
        ('sentence', 'S', 'PUNCT', 'S', 'PUNCT', 'S', 'PUNCT', 'S', 'PUNCT', 'S', 'PUNCT'): 1,
        ('S', 'sn', 'sn', 'grup.verb', 'sn', 'sp', 'S'): 1,
        ('S', 'sn', 'S', 'sp'): 1,
        ('sentence', 'sn', 'grup.verb', 's.a', 'S'): 1,
        ('S', 'PUNCT', 'sn', 'S', 'PUNCT', 'inc', 'S', 'PUNCT', 'inc', 'S'): 1,
        ('S', 'conj', 'grup.verb', 'sp', 'sn'): 1,
        ('S', 'S', 'sadv', 'sn', 'PUNCT'): 1,
        ('grup.adv', 'grup.adv', 'conj', 'grup.adv'): 1,
        ('S', 'conj', 'S', 'conj', 'S', 'PUNCT', 'inc', 'S', 'PUNCT', 'inc', 'S', 'sn', 'PUNCT'): 1,
        ('sentence', 'sp', 'grup.verb', 'PUNCT'): 1,
        ('spec', 'DET', 'DET', 'DET'): 1,
        ('sentence', 'sn', 'sadv', 'grup.verb', 'S', 'PUNCT'): 1,
        ('sn', 'sn', 'sadv'): 1,
        ('S', 'sn', 'neg', 'grup.verb', 'PUNCT'): 1,
        ('sn', 'sn', 'PUNCT', 'sn', 'conj', 'S', 'PUNCT'): 1,
        ('S', 'grup.a'): 1,
        ('S', 'conj', 'sp', 'grup.verb', 'sn', 'S'): 1,
        ('grup.cs', 'ADV', 'ADP', 'SCONJ'): 1,
        ('sentence', 'grup.verb', 'sp', 'PUNCT', 'prep', 'sn', 'PUNCT'): 1,
        ('S', 'sn', 'sadv', 'grup.verb', 'S', 'PUNCT'): 1,
        ('sentence', 'sadv', 'sn', 'grup.verb', 'sn', 'PUNCT'): 1,
        ('sn', 'sn', 'interjeccio', 'sn'): 1,
        ('interjeccio', 'PROPN'): 1,
        ('sentence', 'S', 'conj', 'S', 'sp', 'PUNCT'): 1,
        ('sentence', 'sn', 'sadv', 'grup.verb', 's.a', 'sn', 'PUNCT'): 1,
        ('grup.nom', 'NOUN', 'sp', 'sn'): 1,
        ('S', 'morfema.verbal', 'grup.verb', 'S'): 1,
        ('S', 'conj', 'sp', 'morfema.verbal', 'grup.verb', 'sn'): 1,
        ('sentence', 'sp', 'morfema.verbal', 'grup.verb', 'PUNCT', 'inc', 'PUNCT'): 1,
        ('inc', 'sn', 'S'): 1,
        ('grup.nom', 'NOUN', 'sp', 's.a', 'sp', 'sadv'): 1,
        ('sentence', 'conj', 'S', 'PUNCT', 'S', 'PUNCT', 'S', 'PUNCT', 'S', 'PUNCT', 'S', 'PUNCT'): 1,
        ('S', 'sn', 'sn', 'sn', 'sp'): 1,
        ('S', 'infinitiu', 'sn', 'sp', 'sadv', 'sp'): 1,
        ('grup.nom', 'PRON', 'ADV'): 1,
        ('sp', 'PUNCT', 'conj', 'morfema.verbal', 'grup.verb', 'sp'): 1,
        ('conj', 'prep'): 1,
        ('prep', 'ADP', 'SCONJ'): 1,
        ('sentence', 'S', 'sn', 'grup.verb', 'sadv', 'PUNCT'): 1,
        ('sadv', 'PUNCT', 'grup.adv'): 1,
        ('sentence', 'sadv', 'grup.verb', 'sp', 'PUNCT', 'S', 'PUNCT'): 1,
        ('sentence', 'sn', 'morfema.verbal', 'grup.verb', 'sadv', 'PUNCT'): 1,
        ('sn', 'sadv', 'NUM', 'PROPN', 's.a', 'S'): 1,
        ('sadv', 'neg', 'ADV', 'ADP'): 1,
        ('grup.nom', 'grup.nom', 'S', 'S'): 1,
        ('sentence', 'S', 'conj', 'sp', 'PUNCT'): 1,
        ('grup.verb', 'VERB', 'ADP', 'infinitiu', 'morfema.pronominal'): 1,
        ('S', 'sp', 'sn', 'morfema.pronominal', 'grup.verb', 'sp'): 1,
        ('S', 'PUNCT', 'gerundi', 'sn', 'S'): 1,
        ('S', 'PUNCT', 'conj', 'sn', 'grup.verb', 'sp', 'sp'): 1,
        ('sentence', 'sp', 'morfema.verbal', 'sn', 'grup.verb', 'sp', 'sn', 'PUNCT'): 1,
        ('grup.nom', 'PRON', 'sp', 'sp', 'sp', 's.a'): 1,
        ('sentence', 'sadv', 'sp', 'sn', 'grup.verb', 'sn', 'PUNCT'): 1,
        ('sentence', 'sp', 'neg', 'morfema.verbal', 'sn', 'grup.verb', 'sp', 'sn', 'sp', 'PUNCT'): 1,
        ('sentence', 'sp', 'grup.verb', 'sn'): 1,
        ('S', 'grup.verb', 'sn', 'sadv'): 1,
        ('sn', 'grup.adv', 'grup.nom'): 1,
        ('grup.adv', 'ADV', 'ADV', 'ADP', 'NUM'): 1,
        ('sentence', 'sn', 'inc', 'PUNCT'): 1,
        ('sentence', 'PUNCT', 'sn', 'grup.verb', 'sn', 'sp', 'sp', 'PUNCT'): 1,
        ('grup.nom', 's.a', 'sp', 'sp'): 1,
        ('sentence', 'sp', 'sp', 'sn', 'grup.verb', 'sn', 'PUNCT'): 1,
        ('grup.nom', 'NOUN', 's.a', 'sp', 'sp', 'S'): 1,
        ('sentence', 'sp', 'S', 'sn', 'grup.verb', 'sp', 'PUNCT'): 1,
        ('grup.nom', 'PROPN', 's.a', 'S'): 1,
        ('S', 'sp', 'grup.verb', 'sn', 'sn', 'sp'): 1,
        ('S', 'infinitiu', 'sp', 'sn', 'PUNCT'): 1,
        ('sentence', 'sn', 'sp', 'grup.verb', 'sn', 'sp', 'PUNCT'): 1,
        ('sp', 'sp', 'PUNCT', 'sn'): 1,
        ('grup.nom', 'PROPN', 'NOUN', 'sn', 'sn'): 1,
        ('grup.nom', 'PROPN', 'S', 'S'): 1,
        ('sentence', 'sp', 'grup.verb', 'sadv', 'sn', 'PUNCT'): 1,
        ('S', 'sp', 'morfema.verbal', 'sn', 'grup.verb', 'sp', 'sn', 'PUNCT'): 1,
        ('S', 'S', 'sn', 'grup.verb', 'sn', 'sp', 'sp'): 1,
        ('S', 'PUNCT', 'conj', 'sn', 'grup.verb', 's.a', 'PUNCT'): 1,
        ('sentence', 'sp', 'morfema.verbal', 'grup.verb', 'sp', 's.a', 'S', 'PUNCT'): 1,
        ('S', 'infinitiu', 'sadv', 'sn'): 1,
        ('grup.nom', 'grup.nom', 'NOUN'): 1,
        ('sentence', 'S', 'sn', 'sn', 'grup.verb', 'S', 'PUNCT'): 1,
        ('S', 'PUNCT', 'sp', 'sn', 'grup.verb', 'sp', 'sn'): 1,
        ('sentence', 'sn', 'grup.verb', 'sp', 'sn', 'sp', 'PUNCT'): 1,
        ('sentence', 'S', 'conj', 'S', 'PUNCT', 'PUNCT'): 1,
        ('S', 'sp', 'grup.verb', 'S', 'PROPN'): 1,
        ('sn', 'PUNCT', 'grup.nom', 'PUNCT', 'PUNCT'): 1,
        ('grup.a', 'PROPN'): 1,
        ('sp', 'PUNCT', 'sadv', 'infinitiu', 'sn'): 1,
        ('sadv', 'prep'): 1,
        ('prep', 'ADP', 'ADV'): 1,
        ('S', 'sadv', 'participi', 'sadv'): 1,
        ('sentence', 'sn', 'neg', 'grup.verb', 'sn', 'sp', 'S', 'sn', 'PUNCT'): 1,
        ('S', 'PUNCT', 'conj', 'neg', 'grup.verb', 'S'): 1,
        ('sentence', 'sadv', 'S', 'S', 'PUNCT'): 1,
        ('S', 'sn', 'neg', 'grup.verb', 'sn', 'sp'): 1,
        ('S', 'sn', 'grup.verb', 'sp', 'sn', 'sp'): 1,
        ('sp', 'PUNCT', 'sadv', 'infinitiu', 'sn', 'sp'): 1,
        ('grup.nom', 'grup.a', 's.a'): 1,
        ('S', 'sn', 'grup.verb', 'sp', 'sp', 'sadv'): 1,
        ('grup.prep', 'ADJ', 'ADP'): 1,
        ('sadv', 'sadv', 'S'): 1,
        ('sn', 'spec', 'grup.a'): 1,
        ('grup.a', 'grup.w', 's.a'): 1,
        ('grup.w', 'ADJ', 'sp'): 1,
        ('grup.nom', 'grup.nom', 'sp', 's.a'): 1,
        ('S', 'sn', 'grup.verb', 'sp', 'sadv'): 1,
        ('sadv', 'PUNCT', 'sn', 'sadv'): 1,
        ('S', 'infinitiu', 'morfema.pronominal', 'grup.verb', 'sn'): 1,
        ('S', 'grup.verb', 'sadv', 'PUNCT'): 1,
        ('infinitiu', 'infinitiu', 'VERB'): 1,
        ('S', 'sn', 'grup.verb', 'sp', 'sp'): 1,
        ('S', 'grup.verb', 'sp', 'sp', 'S'): 1,
        ('S', 'PUNCT', 'conj', 'sp', 'morfema.verbal', 'sn', 'grup.verb', 'sn'): 1,
        ('sentence', 'S', 'inc', 'S', 'PUNCT'): 1,
        ('S', 'conj', 'S', 'conj', 'S', 'PUNCT', 'S', 'PUNCT', 'S', 'conj', 'S'): 1,
        ('S', 'infinitiu', 'sadv', 'sp', 'sp', 'sn', 'sp'): 1,
        ('grup.nom', 'ADJ', 'S'): 1,
        ('S', 'sadv', 'grup.verb', 'sn', 'sp'): 1,
        ('S', 'grup.verb', 'S', 'PUNCT'): 1,
        ('S', 'participi', 'sp', 'sn'): 1,
        ('S', 'sp', 'sn', 'grup.verb', 's.a', 'sp'): 1,
        ('s.a', 'PUNCT', 's.a', 'conj', 'sadv', 'PUNCT'): 1,
        ('sentence', 'S', 'sn', 'sn', 'sn'): 1,
        ('sn', 'PUNCT', 'sn'): 1,
        ('S', 'sadv', 'grup.verb', 'sp', 'S'): 1,
        ('S', 'sn', 'sp', 'grup.verb', 'sn'): 1,
        ('S', 'PUNCT', 'PUNCT', 'S'): 1,
        ('S', 'S', 'PUNCT', 'sadv', 'PUNCT', 'grup.verb', 'PUNCT', 'S', 'PUNCT'): 1,
        ('S', 'PUNCT', 'S', 'conj', 'S', 'PUNCT'): 1,
        ('S', 'S', 'conj', 'grup.verb'): 1,
        ('grup.verb', 'infinitiu', 'sadv', 'sn'): 1,
        ('S', 'S', 'sn', 'sn', 'grup.verb', 'PUNCT'): 1,
        ('S', 'conj', 'sadv', 'sn', 'grup.verb', 'PUNCT'): 1,
        ('S', 'S', 'PUNCT', 'sn', 'sn', 'sn', 'grup.verb'): 1,
        ('S', 'conj', 'neg'): 1,
        ('grup.nom', 'DET'): 1,
        ('sentence', 'S', 'grup.verb', 'sp', 'sp', 'PUNCT'): 1,
        ('S', 'sn', 'grup.verb', 'sadv', 'sn', 'sp', 'sn'): 1,
        ('grup.nom', 's.a', 'NOUN', 'sp', 'inc'): 1,
        ('grup.nom', 'NOUN', 's.a', 'S', 'sp'): 1,
        ('sentence', 'PUNCT', 'S', 'conj', 'PUNCT', 'sp', 'NUM', 'PUNCT'): 1,
        ('sentence', 'sn', 'grup.verb', 'sp', 'sp', 'sp', 'PUNCT', 'sn', 'PUNCT'): 1,
        ('S', 'conj', 'S', 'sp'): 1,
        ('sentence', 'sp', 'grup.verb', 'sp', 'sp', 'PUNCT'): 1,
        ('S', 'PUNCT', 'sadv', 'participi', 'sn', 'PUNCT', 'grup.z', 'S', 'morfema.verbal', 'grup.verb', 'sp', 'sp'): 1,
        ('S', 'S', 'PUNCT', 'inc', 'S', 'PUNCT', 'S', 'PUNCT', 'S'): 1,
        ('S', 'sn', 'grup.verb', 'sn', 'sp', 'S'): 1,
        ('S', 'gerundi', 'sp', 'sn'): 1,
        ('S', 'S', 'PUNCT', 'inc', 'S', 'PUNCT'): 1,
        ('S', 'S', 'PUNCT', 'conj', 'S'): 1,
        ('S', 'sn', 'sn', 'grup.verb', 'sp', 'sp', 'sp'): 1,
        ('sn', 'spec', 'S'): 1,
        ('S', 'infinitiu', 'morfema.pronominal', 'sn', 'sp'): 1,
        ('S', 'sn', 'sp', 'grup.verb', 'sn', 'sp', 'PUNCT'): 1,
        ('S', 'S', 'grup.verb', 'sp', 'PUNCT'): 1,
        ('S', 'morfema.verbal', 'grup.verb', 'sp', 'sp'): 1,
        ('sentence', 'inc', 'sp', 'sn', 'grup.verb', 'sp', 'sadv', 'PUNCT'): 1,
        ('S', 'PUNCT', 'conj', 'sn', 'grup.verb', 'sn'): 1,
        ('sentence', 'sn', 'sadv', 'grup.verb', 'sp', 'PUNCT'): 1,
        ('sentence', 'sn', 'grup.verb', 'sp', 'conj', 'S', 'PUNCT'): 1,
        ('S', 'sn', 'grup.verb', 'sp', 'sn', 'PUNCT'): 1,
        ('sentence', 'morfema.verbal', 'grup.verb', 'sp', 'sn', 'S', 'PUNCT'): 1,
        ('S', 'S', 'sp', 'PUNCT'): 1,
        ('participi', 'VERB'): 1,
        ('S', 'neg', 'grup.verb', 'S', 's.a'): 1,
        ('s.a', 'grup.adv'): 1,
        ('sentence', 'NUM', 'PUNCT', 'S', 'PUNCT'): 1,
        ('sentence', 'sn', 'sn', 'sp', 'morfema.verbal', 'grup.verb', 'sn', 'PUNCT', 'conj', 'S', 'PUNCT'): 1,
        ('sentence', 'S', 'conj', 'S', 'PUNCT', 'S', 'PUNCT', 'S', 'PUNCT'): 1,
        ('sn', 'sn', 'S', 'PUNCT'): 1,
        ('S', 'relatiu', 'grup.verb', 'S'): 1,
        ('S', 'sn', 'sp', 'sp', 'sp', 'sp'): 1,
        ('S', 'sn', 'morfema.verbal', 'grup.verb', 'sn', 'PUNCT'): 1,
        ('S', 'sn', 'morfema.verbal', 'grup.verb', 'sp', 'PUNCT'): 1,
        ('sentence', 'sn', 'sn', 'grup.verb', 'sn', 'S', 'PUNCT'): 1,
        ('S', 'PUNCT', 'conj', 'neg', 'morfema.verbal', 'grup.verb', 'sp'): 1,
        ('sentence', 'morfema.pronominal', 'grup.verb', 's.a', 'sn', 'S', 'PUNCT'): 1,
        ('sn', 'sn', 'PUNCT', 'sn', 'conj', 'sn', 'conj', 'sn'): 1,
        ('grup.nom', 'NOUN', 'sp', 's.a', 'S'): 1,
        ('S', 'PUNCT', 'conj', 'neg', 'grup.verb', 'sp', 'sn'): 1,
        ('sentence', 'PUNCT', 'sadv', 'participi', 'sn', 'sp', 'PUNCT', 'inc', 'sn'): 1,
        ('S', 'PUNCT', 'S', 'sn', 'PUNCT', 'PUNCT'): 1,
        ('sn', 'sn', 'PUNCT', 'NUM', 'NUM'): 1
    }
)

print(f"nodos de largo 2: {len([n for n in node_count if len(n) == 2])}")

